import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer/footer";

export const metadata: Metadata = {
  title: "Zentry: The Metagame",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative min-h-screen w-screen overflow-x-hidden no-scrollbar`}
      >
        <Navbar />  
        {children}
        <Footer />
      </body>
    </html>
  );
}

