import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Zentry: The Metagame",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative min-h-screen w-screen overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}

