import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer/footer";
import { ContextProvider } from "@/providers/homeContext";

export const metadata: Metadata = {
  title: "Zentry: The Metagame",
  description: "Generated by create next app",
  icons: {
    icon: "/img/logo/primaryBG_logo_large.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative min-h-screen w-screen overflow-x-hidden no-scrollbar`}
      >
        <ContextProvider>
          <Navbar />  
          {children}
          <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}

